#!/bin/bash

echo "=========================================="
echo "Session Persistence Test Script"
echo "=========================================="
echo ""
echo "This script will help you test session persistence."
echo ""
echo "TEST INSTRUCTIONS:"
echo ""
echo "1. Start the dev server (if not already running):"
echo "   npm run dev"
echo ""
echo "2. Open browser and go to: http://localhost:8080"
echo ""
echo "3. Log in with your phone number and OTP"
echo ""
echo "4. Once logged in, perform these tests:"
echo ""
echo "   TEST 1: Page Refresh"
echo "   - Press F5 or Cmd+R"
echo "   - ✅ You should remain logged in"
echo ""
echo "   TEST 2: Browser Close/Reopen"
echo "   - Close the browser completely"
echo "   - Reopen and visit http://localhost:8080"
echo "   - ✅ You should be automatically logged in"
echo ""
echo "   TEST 3: New Tab"
echo "   - Open a new tab"
echo "   - Navigate to http://localhost:8080"
echo "   - ✅ You should already be logged in"
echo ""
echo "   TEST 4: Logout"
echo "   - Click the logout button"
echo "   - Refresh the page"
echo "   - ✅ You should be on the login page"
echo ""
echo "   TEST 5: localStorage Check"
echo "   - Open browser DevTools (F12)"
echo "   - Go to Application tab → Local Storage"
echo "   - Look for firebase:authUser key"
echo "   - ✅ You should see auth token data"
echo ""
echo "=========================================="
echo "All tests passed? Session persistence works!"
echo "=========================================="

